### ISSUE TITLE
Appendix table header is missing a background

### ISSUE THREAD

**Issue by gustavi** [github/choosealicense.com#1110]
The URL : https://choosealicense.com/appendix/

The bug :

![image](https://github.com/github/choosealicense.com/assets/2736557/bcb5b72d-a817-4f74-a81e-ed390b306bf1)

**Comment by mlinksva** [comment]
Only pertinent when scrolling beyond initially visible portion of table, introduced in #1089. I noticed this then, and decided it is a feature rather than a bug; no reason to obscure info that'd otherwise be visible. I guess if there's some way to giving the header a semi-opaque background so that it is clear it is not a bug, I'd be open to doing that.

**Comment by matthijsgroen** [comment]
Please make the sticky header more readable.
