### ISSUE TITLE
License: Pick any open source license 

### ISSUE THREAD

**Issue by ShalokShalom** [github/choosealicense.com#1159]
Is there a license, that says "pick any OCI license you want"?

I would like to give freedom, which license is used. 
I think, its easy to design a license, that does that?

**Comment by ShalokShalom** [comment]
Another idea could be, to simply license multiple times. 

So, similar to a dual license, could I license under [12 different](https://opensource.org/licenses/?categories=popular-strong-community) licenses? 

How would that look like?

**Comment by mlinksva** [comment]
Kind of https://www.mysql.com/about/legal/licensing/foss-exception/ which now is https://oss.oracle.com/licenses/universal-foss-exception/ though is limited to certain uses.

Yes you could license under a large number of licenses (even "all" of them, [joke](https://gondwanaland.com/mlog/2012/12/21/cc-multi-licensed/) from non-software licensing), though if any of them is permissive, there's little point, just one permissive license is enough. That's why the exception above is used with copyleft licenses.

You could design a copyleft license that allows derivatives (without any limitations like the exception above) to be licensed under any OSS license, but the use case would be pretty narrow -- unable to use material under any other copyleft license in a project under this hypothetical license, and permissive licensed projects would avoid material under the hypothetical license, because even though they could use the material, if they did so they effectively would no longer be permissive -- so the use case would be to be a universal donor to only copyleft projects. Which would be fine, but there doesn't seem to be much demand for such a thing. [copyleft-next](https://github.com/copyleft-next/copyleft-next) itself an experiment, does this partially (it's a donor to any version of the GPL). Anyway, it's an idea that comes up now and again, in fact did for me [recently](https://twitter.com/mlinksva/status/1740090860241612914) as a way to test someone's ChatGPT-based license classifier, with the following (totally made up, do not use, does not work, etc, thus strikethrough to, er, underline the point) text:

<s>
Permission is hereby granted, free of charge, to any person obtaining a copy of the material associated with this license (the "Material"), to deal in the Material without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Material and to permit persons to whom the Material is furnished to do so, subject to the following conditions:
 
Provenance. Provide with all copies or substantial portions of the Material, (1) a copy of or unambiguous reference to this license, and credit reasonable to the medium, means, and context, at least as prominent as other comparable credits, and (2) if licensors have provided a resource, such as a version control repository, containing any credits or legal notices for the Material, a link to that resource, or a reasonable substitute containing the same information.

Openness. License Adaptations of the Material under terms that allow anyone to freely access, use, modify, and share the Adaptations for any purpose (conditioned, at most, on the preservation of provenance and openness). Licenses that meet the criteria of the Free Software Definition, Open Definition, or Open Source Definition satisfy this condition.
 
THE MATERIAL IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE MATERIAL.
</s>

In any case, using the FOSS [interface] exception above, or multi-licensing, or making up new licenses, are all niche and not within scope for this project. But curious question, thus the ramble.
