### ISSUE TITLE
"No license" does not allow commercial or private use

### ISSUE THREAD

**Issue by asb** [github/choosealicense.com#196]
Currently the [page for "no license"](http://choosealicense.com/licenses/no-license/) marks "Commercial Use" and "Private Use" as permitted, but this is false. You could argue that the Github TOS allow private use (as it explicitly says that you consent to public projects being forkable) but this doesn't apply elsewhere and it's still not something I'd rely on.

**Comment by benbalter** [comment]
This was previously discussed, but I'm not finding the directly relevant issue (halp?). Two that may provide some context are https://github.com/github/choosealicense.com/pull/115 and https://github.com/github/choosealicense.com/pull/25.

**Comment by haacked** [comment]
Yeah, this is a good point. Want to submit a PR?

**Comment by benbalter** [comment]
The counter argument, is that there's always an implied license for _some_ use. You need to distinguish between unlicensed code knowingly posted publicly, and code sitting on my computer, which I neither post nor license. 

If the New York Times posts a news story on their website, there's an implied license for private use in that I am allowed to read it, print it, email it to a friend, etc. If I were a company, I could probably cut it out of the print edition and put it on my wall (e.g., a restaurant review).

There's some implied license for use for code knowingly posted publicly. If I wrote a blog post with a code snippet in it (or post it to stack exchange, etc.), you'd likely feel comfortable taking that one line and using it in a script you're writing for personal use, even without a formal license. Not sure where the line is.

**Comment by haacked** [comment]
Thanks for the clarification @benbalter.

**Comment by cubiclesoft** [comment]
Without a license, a developer opens themselves up to lawsuits.  There is a reason that licenses include the words "WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT." and then proceeds to include further statements about no liability.  Lawyers wrote and vetted such language because, without it, if the code "causes harm" (usually traceable to financial loss), the developer may be held liable for damages.

The argument about the New York Times is false.  The NYT has a Terms of Service document that clearly spells out what may and may not be done with their content:

https://www.nytimes.com/content/help/rights/terms/terms-of-service.html#b

In essence, they clarify their claim on their copyright materials and their lawyers put that document together.  There is no implied license since their claim on their content is clearly written and communicated.

Failure to specify the allowances or limitations on copyright protected software means that the author can come along later and claim that those using the code have infringed on their copyright.  And then they can claim damages.  As a result, I agree with the original poster that both Commercial and Private Use should be moved to the Forbidden column.  I also recommend that the 'no-license' page be changed to include the legal risks that will be undertaken by the author for NOT having a license.

**Comment by benbalter** [comment]
Anyone else have a strong opinion on this issue?

**Comment by unhammer** [comment]
Without granting a license, only the copyright holder can use the code for whatever purpose. So commercial/private use should be in the forbidden column, since the "use" refers to what people _other than the copyright holder_ can do with the code.

Regarding posting code snippets on a blog or whatever, at least here in Norway what matters is if the code is substantial enough to be a "Work". If it's a Work, then it's copyrightable, if not, it's basically public domaon. (There's no hard line as to where it becomes a Work, although the FSF starts requiring copyright assignment after about 14 lines of code so presumably their lawyers have some reason for that.) And if your code is copyrightable and you haven't said or implied otherwise, only _you_ have the right to use it.

IANAL, but I am certain that explicitly claiming that a "No license" grants rights to Commercial and Private use as http://choosealicense.com/licenses/no-license/ does is outright wrong.

**Comment by mlinksva** [comment]
Re-opening. The current properties of "no license" aren't aligned with their use for actual licenses, which concern express permissions and requirements/prohibitions conditioning/scoping those. I'll open a PR later to address.
