### ISSUE TITLE
Licenses missing from sitemap

### ISSUE THREAD

**Issue by benbalter** [github/choosealicense.com#203]
E.g., http://choosealicense.com/sitemap.xml

@parkr and idea why `jekyll-sitemap` wouldn't include the license files?

**Comment by parkr** [comment]
> @parkr and idea why jekyll-sitemap wouldn't include the license files?

They're not `html` files: https://github.com/jekyll/jekyll-sitemap/blob/master/lib/jekyll-sitemap.rb#L11

I'd suggest adding a field to the page which says:

``` yaml
---
title: Blah
sitemap:
  include: true
```

It's a little confusing ("isn't everything included?") but would allow you to carry on with just TXT files.

**Comment by benbalter** [comment]
> They're not html files:

Oh odd. Even though the permalink ends in an implied `.html`?

**Comment by parkr** [comment]
> Oh odd. Even though the permalink ends in an implied .html?

Right. Jekyll sees them as text files, and it asks the converter for this file (the identity converter in this case) what output extension the file will have and asks if it's `.html`. If not, it gets the :boot:. We could also test the `permalink` attribute in jekyll-sitemap if you like!

Side question: why are the licenses .txt files rather than .html files in this repo, anyway?

**Comment by benbalter** [comment]
> Side question: why are the licenses .txt files rather than .html files in this repo, anyway?

Because the body is text, not HTML.

**Comment by benbalter** [comment]
Fixed via https://github.com/jekyll/jekyll-sitemap/issues/39

**Comment by parkr** [comment]
:boom:
