### ISSUE TITLE
Consider discussing ecosystems with an already predominant license

### ISSUE THREAD

**Issue by strugee** [github/choosealicense.com#239]
I'm not really sure whether this belongs here or not, so I want to have a discussion about it.

It would be nice if we mention somewhere that one consideration might be that if you're working within a particular ecosystem, you might want to consider using a particular license that dominates that ecosystem.

Examples:
- MPL for Mozilla
- EPL for Eclipse
- Apache or (less commonly) the GPL for Android
- MIT for Ruby gems (as I understand it - I'm not a Ruby person)
- MIT for JS, including NPM
- GPLv3 for official GNU projects (not sure if this is significant enough)
- GPL for GNU/Linux in general

**Comment by bhuga** [comment]
What workflow are you seeing for this?

Is it `I know my ecosystem: help me find a license for it.` ?

Or is it `Here's some more information about the MPL license you're looking at: the mozilla community uses it.` ?

I think I would be okay with the second format, but would fear that adding an "ecosystem route" through the site might dilute the main goals we're after. Rather than educating, it would just tell you what bucket you belong in. Sort of like a facebook quiz: what open source license are you?

That's just a quick off-the-cuff opinion, though, so I'm happy to hear other opinions.

**Comment by strugee** [comment]
> `Is it I know my ecosystem: help me find a license for it.` ?

Yeah, this is basically what I meant. I would phrase it as: `I'm undecided, I'll just go with the flow`, but yeah.

> Rather than educating, it would just tell you what bucket you belong in.

I share your concerns; I mostly wanted to see if anyone else didn't.
