### ISSUE TITLE
Add the AGPL license

### ISSUE THREAD

**Issue by adamretter** [github/choosealicense.com#269]
Several commercial projects seem to use the AGPL license to both permit Open Source and protect their investment. For example - http://osswatch.jiscinvolve.org/wp/2014/09/10/locked-into-free-software-unpicking-kualis-agpl-strategy/

**Comment by strugee** [comment]
I'd like to make somewhat of a radical suggestion and say that we should universally recommend the AGPL instead of GPLv2/v3. If you are using the GPLv2 in the way that it is intended - to ensure the freedom of downstream works - then there is virtually no reason that you wouldn't upgrade to the GPLv3 or even all the way to the AGPL.

IMHO, the main reason that the GPLv3/AGPL hasn't been adopted is simply inertia, not because of any flaw in the licenses themselves.

**Comment by adamretter** [comment]
@strugee From my perspective there is one important difference between GPL and AGPL and I think this website is the perfect place to show that in a simple manner.

**Comment by strugee** [comment]
@adamretter there is an important difference, yes. But I don't think it's important enough to recommend all three GPLs. The title for the GPL section on the front page says: "I care about sharing improvements." If that's true, why would the user use the GPL instead of the AGPL?

**Comment by adamretter** [comment]
@strugee well I guess what I am suggesting is that "I care about sharing improvements" is not the right title. For AGPL, you could say "I want to achieve open source vendor lock-in"

**Comment by strugee** [comment]
@adamretter the way I see it, _all_ the GPL licenses (not just the AGPL) can be used either in the true free software spirit - in the way that the website suggests currently - or it can be used to promote "open source vendor lock-in," as you put it.

We shouldn't encourage the second one, IMO. ChooseALicense is fundamentally about getting people to release their stuff as free software, and the use that you've suggested is the antithesis to that. Therefore, we should keep the original license description, both because that is what we as a project (presumably) want to encourage as well as the fact that that's the original intended use of the AGPL.

Yes, in a certain sense, the AGPL can be used to achieve bad things. But that applies just as equally to the GPL. Anyone who is motivated enough to want to use the GPL in such a way will certainly know about the AGPL too, so us suggesting the GPL on the front page instead of the AGPL in order to prevent this situation (which I believe is what you're suggesting) is sacrificing a _lot_ of projects that could be under the strongest copyleft available in order to maybe, _maybe_ prevent something bad from happening.

**Comment by benbalter** [comment]
> Add the AGPL license

@adamretter what do you mean? It's already listed: https://github.com/github/choosealicense.com/blob/gh-pages/_licenses/agpl-3.0.txt

**Comment by adamretter** [comment]
@benbalter Somehow the buttons on the licenses page did not stand out for me and so I completely missed them. Now you mention it, I see it is here http://choosealicense.com/licenses/#agpl-v3. Sorry for the noise.
