### ISSUE TITLE
Open hardware licenses and choosealicense.com?

### ISSUE THREAD

**Issue by mithro** [github/choosealicense.com#313]
The choosealicense.com site is pretty awesome! 

I was wondering with the growth of open hardware (which are increasingly hosted on github) if it would make sense to add another link in the "My content isn’t code." section for hardware projects. I would have sent a pull request but I couldn't figure out were the right place to link too would be, there doesn't seem to be a similar site - the "best" I found so far was http://www.inmojo.com/licenses/ and that isn't exactly clean/simple like this site.

Generally it seems for hardware;
- For "simple+permissive" most people seem go with CC-BY or BSD/MIT license
- For "care about sharing" the 3 major choices seem to be;
  - CC-BY-SA
  - TAPR Open Hardware License (OHL) - http://www.tapr.org/OHL
  - CERN Open Hardware License - http://www.ohwr.org/projects/cernohl/wiki
- I don't know enough to figure out the "I care about patents" bit..

Thoughts?

**Comment by stapelberg** [comment]
+1.

I was about to submit a pull request for the CERN OHL, just so that it can be detected by https://github.com/benbalter/licensee and exposed by the GitHub license API as a consequence :). Would such a PR be accepted?

**Comment by mlinksva** [comment]
By [use](http://www.oshwa.org/oshw-community-survey-2013/#section5) (2013, but license use changes slowly; anyone with data better in recency or other dimension, please share) the major copyleft family options are CC-BY-SA and GPL. Note the most recent versions of those recently were [made compatible](https://creativecommons.org/weblog/2015/10/08/46186) in a limited (one-way) fashion. The CERN and TAPR licenses are incompatible with everything else, including each other. Promoting such fragmentation would be a bad thing to do.

The best options for hardware designs in any category are the same as the best options for software. Perhaps this should be communicated on the site in some manner. This also answers "care about patents" -- Apache 2. CC instruments should not be recommended for hardware or software due to their explicit caring about patents in an anti-sharing direction: explicit non-grant.

I agree it would be nice to be able to detect the CERN OHL and a whole bunch of other licenses, which can be otherwise [hidden](https://github.com/github/choosealicense.com/issues/273). But I suspect a general decision to support (or not) detecting lots more licenses should be made before adding such one at a time.

**Comment by benbalter** [comment]
>  But I suspect a general decision to support (or not) detecting lots more licenses should be made before adding such one at a time.

Opened https://github.com/github/choosealicense.com/issues/315 as a tracking issue to document and discuss, but at first glance, I don't see any reason not to add hardware licenses as hidden assuming they achieve some baseline for notoriety/adoption/differentiation.

**Comment by benbalter** [comment]
As discussed, please see the [updated criteria for adding a new license](https://github.com/github/choosealicense.com/blob/gh-pages/CONTRIBUTING.md#adding-a-license). I don't believe the TAPR or CERN licenses have SPDX IDs yet.

**Comment by mlinksva** [comment]
Addressed with #359

**Comment by StEvUgnIn** [comment]
Now might be a very good time to reassess CERN OHL https://spdx.org/licenses/
