### ISSUE TITLE
Recommend AGPL3, LGPL3 and GPL3

### ISSUE THREAD

**Issue by ionas** [github/choosealicense.com#331]
AGPL3, GPL3 and LGPL3 really differ.

My gut feeling tells me most of the projects on github want either AGPL3 or LGPL3 and possibly not GPL3 (that would be for the tiny fraction that are "desktop" or "mobile" open source binary/packaged/distributed/standalone apps)
- GPL3 enforces share-back on software that is being distributed as a package or binary (App Store, Download, Install, whatever)
- AGPL3 enforces share-back and considers server-only software (PaaS, cloud, webhosting, etc) to be a distribution. This is the case for a big majority of apps on github.
- LGPL3 goes more towards the MIT road of being easy to integrate with closed source infrastructure but still enforces share-back if you want to distribute software, for the library part. E.g. it **is** ~~not~~ **a good** license for a library that is being bundled with other apps while it is a bad license for libraries that you want to have share-back on but that run as part of sever software only (see AGPL3).

E.g. LGPL3 is very much the competition for MIT, while AGPL3 is **MOST LIKELY** the choice for those that **might accidentally chose GPL3**. The current info page totally misses on the last point and hides the competition and differences between LGPL3 and MIT. Both must be fixed in order to respect premise # 1:

> Non-judgmental. Our goal is to help you find a license that meets your goals.

Last but not least, CC is not only for creative stuff. It is very customaziable to go towards public domain (CC0) or non-commercial-shake-alike and things like that.

The current overview is very biased towards the MIT, not only by its primary position in the list, but also because GPL (packaged software) LGPL (packaged software library) and AGPL (server software) is not differentiated, e.g. not communicating what benefits a developer, organization or company might get by choosing one of those.

On 16-01-29 13:03, Ivan Žužak wrote:

> Hi Jonas,
> 
> Can you open an issue on the project's issue tracker?
> 
> https://github.com/github/choosealicense.com
> 
> Thanks,
> Ivan
> 
> > > http://choosealicense.com/
> > > 
> > > This should REALLY mention AGPL3 and LGPL3 instead of GPL3 as these two are probably much more fitting for all the projects on github than just GPL3.

Edit: fixed wrong negation above.

**Comment by mlinksva** [comment]
I suspect the first premise was weighed with another:

> The homepage should have just enough to help 99% of folks make a decision.

I actually agree with your analysis for the most part that LGPL or AGPL might better represent ends that projects wanting to force sharing might have, but GPL is vastly more popular so highlighting that is very non-judgemental relative to practice/conventional wisdom.

I haven't looked closely at copyleft licenses on choosealicense.com yet but my off the cuff thoughts are:
- GPLv2 vs GPLv3 way too small a concern to highlight on home page. New projects should just use v3. Folks contributing to an existing v2 project or who care about the differences aren't really in need of this site.
- I'd like to represent the range of copyleft scope from MPL->LGPL->GPL->AGPL probably on the /licenses page rather than the home page though, and haven't thought at all about how to do it.

Regarding CC, the choosealicense.com home page does not say it is only for creative stuff, it says "isn't code". I don't think that's quite right, in part because open source software licenses are often the best licenses for "non-code" and the link to CC doesn't help people get a license in a format that is easy to include in a source repository and it does provide licenses that don't meet our [criteria](https://github.com/github/choosealicense.com/blob/gh-pages/CONTRIBUTING.md#adding-a-license). CC0 is represented on /licenses. #307 and #33 are related and I hope to improve the site in this regard in the coming weeks.

I don't think there's anything immediately actionable in this issue but I'll leave it open a over the weekend for discussion purposes. Thanks for your feedback!

**Comment by ionas** [comment]
A helping page should HELP with choosing a good license (be it AGPL3, LGPL3, MIT or CC0 for instance) for future projects. Because of that I'd offer AGPL3 / LGPL3 / GPL3 next to each other. Picking GPL for something like wordpress might be good for the wordpress.com corp but is certainly not good for the community project contributors that are not involved with wordpress.com as it mis-advertises what the GPL will do for them (or won't!).

The spectrum of AGPL3, GPL, LGPL3, MIT, CCO is really relevant IMHO for picking new licenses (I have had no issues with patents and little knowledge, but you covered that already on your page).

CC licenses go beyond source code licenses as you figured out, too - but for some there is a strong borderline (say icon fonts, or svg libraries). When in doubt if its not only code, CC is a strong contender for sure. E.g. you could copy the vector result of an SVG and repaste it somewhere - the data that got rendered is NOT the source code, yet you will get exactly the same result. CC is probably the license that will touch those issues.

I do agree that the GPL2 vs GPL3 thing does not need to be on the homepage. If you want to pick GPL2 you have a good - backwards compatible and legal integration related - reason, to do so and thus are already _knee deep_ into this... bollox ;).

Thanks for caring :+1: :).

**Comment by germaino** [comment]
Hi,
It is never mentioned that GPL3 has strong installation requirement ? which make a big difference versus GPL2. Am I wrong ?
BR

**Comment by mlinksva** [comment]
@germaino it's mentioned on the current home page as "V3 is similar to V2, but further restricts use in hardware that forbids software alterations." This sentence is going away as GPLv2 is going away from the home page soon, see #362. 

If you're interested in the details of how GPLv3 deals with device lock-down, read the license or an explanation at http://copyleft.org/guide/monolithic/#x1-810009.9.2

**Comment by wolftune** [comment]
I think the lack of obvious clarity about what the AGPL is here is still likely to result in many people who actually desire the AGPL to end up not recognizing it as the thing they want. There needs to be some level of really obvious statement somewhere that if people want to require sharing for software accessed over a server, they need AGPL. Otherwise, people will be misled.

**Comment by ionas** [comment]
@wolftune exactly! The debate between free as in freedom and free as in beer (or copyleft vs public domain-ish) is one thing. If someone chose a copyleft license the one should be well informed on its implications and NOT misled by GPL vs AGPL.
