### ISSUE TITLE
Reorder rules in license pages and elsewhere to match the sequence permissions/conditions/limitations

### ISSUE THREAD

**Issue by waldyrious** [github/choosealicense.com#387]
I'm planning on submitting a PR doing this as soon as #386 is settled.

**Comment by ionas** [comment]
Actually the order conditions > permissions > limitations is really a welcome refresh. So no thanks.

**Comment by waldyrious** [comment]
@ionas I'd like to hear your rationale for preferring that sequence. I feel like permissions > conditions > limitations makes a lot of sense semantically, per the explanation offered by @mlinksva in #361.

**Comment by mlinksva** [comment]
Hmm, the refresh was in the order stated in the title, so I'm confused by your comment @ionas, please do explain.

I believe what @waldyrious is proposing to do here is what I said I hadn't gotten to in #361 --

> I did not reorder the appearance of the groups of properties in license source files (.txt files in _licenses) as those orderings are not used to render anything on the webiste. Might do so later.

Add to that `_data/rules.yml`

**Comment by ionas** [comment]
I reconsidered and I share your point. Just to share my rational anyway:
- I don't consider licenses (or IP) to be a legitimate thing. It is a legal for sure, however.
- As long as it is legal to create licenses/patents and hold copyright I think to those yielding out licenses to 'their' software, the most important part is the conditions part, NOT the permissions part. See Zed Shawn's rant on the AGPL for instance.
- Honest Remark: Furthermore I consider AGPL more free than GPL not less free `because` of its conditions. This is pretty much a thing of perspective and looking over the border of your dish (or choosing not to do so).

From the point of view of `consumers` or rather those that are checking out projects the "Permissions" part is most interesting. However when you are up **to choosing a license** (on this choosealicense.com site ;) you are not advertising your product having a given license and thus permitting a 'consumer'/3rd party developer to join/use your project.

Anyway I can see the reason for both.

Maybe it would be cool to be able to sort by those 2-3 columns - the default being Permissions > Conditions > Limitations or Conditions > Permissions > Limitations.

The change is 'refreshing' compared to the main page. I did not "discover" the separate license page until just recently.

**Comment by mlinksva** [comment]
@ionas thanks for explaining. I'm pretty sympathetic to your rationale: IP is bad, some of the conditions present in open source licenses should instead be regulations, and what is covered by those regulations determined through the usual means of regulation, not by the whim of developers and their employers. But furthering this kind of argumentation is way outside the scope of choosealicense.com. I want the site to communicate how licenses work as accurately as possible, with as little cognitive overhead as possible. Readers can make up their own minds about what license features are most important to them. I don't think any interactive sorting would make /licenses easier to digest. Effectively it is sorted by # of conditions, and I think that's visually quite apparent.
