### ISSUE TITLE
API

### ISSUE THREAD

**Issue by kennydude** [github/choosealicense.com#40]
It should have an API for people to hack with :)

For example, just having http://choosealicense.com/licenses/mit.json would be nice.

I would do it, but I don't know if you guys are happy with a Jekyll plugin or not?

:+1:

**Comment by cobyism** [comment]
Jekyll plugins are not something we can use since the site is hosted using GitHub Pages (where plugins are disabled for security reasons). I do agree with the idea of exposing licenses in a way where machine-consumability is more convenient though, so if there’s a way to do it without a Jekyll plugin I’m sure we’d be open to it :smiley:

**Comment by kennydude** [comment]
I thought that would be the case :(

I wish Jekyll itself would allow a template to have multiple outputs

**Comment by tekkub** [comment]
You could, theoretically, make a page like [licenses.html](https://github.com/github/choosealicense.com/blob/gh-pages/licenses.html) that renders json data instead of HTML.  That trick is often used to generate [RSS feeds](https://github.com/tekkub/tekkub.github.com/blob/master/atom.xml) with jekyll.

**Comment by benbalter** [comment]
:boom:: #47
