### ISSUE TITLE
Expose licenses listed on `/licenses` in a machine-readable format

### ISSUE THREAD

**Issue by benbalter** [github/choosealicense.com#434]
Since https://github.com/github/choosealicense.com/commit/5052d34b11ab414259942f0b6e2c5195fb89b5dc there is no machine-readable way to distinguish the prominence of e.g., MIT from WTFPL.

Before we had:
- Featured
- Normal
- Variant
- Hidden

Now we have:
- Featured
- Everything else

When used elsewhere, e.g., the GitHub API, licensee, it'd be useful to have the prominence implicit in the  hard coded list in https://github.com/github/choosealicense.com/blob/gh-pages/licenses.html exposed in the licenses themselves.

I'm not sure what the name for that flag should be (intuitively, I think `hidden: true` as a default like we had before, and having `hidden: false` on those licenses makes sense, along with updating the template logic to be dynamic), but even having those featured licenses as an array in the template's YAML front matter (even if that wouldn't help expose the licenses) would feel better, from a DRY perspective (rather than hard coding them).

/cc @mlinksva

**Comment by benbalter** [comment]
cc https://github.com/github/choosealicense.com/pull/398

**Comment by mlinksva** [comment]
I did think about ordering by # of conditions and filtering by hidden to make #386 but felt it just made the source for that page more obscure. But sure, having the ordering specified in the front matter of licenses.html or perhaps _config.yml could be useful so that ordering is available if someone wants to do something else with it. I'll think about that and maybe make a PR.

I'll make a PR shortly to re-add hidden: false field on the licenses currently on /licenses because it is useful elsewhere.
