### ISSUE TITLE
Website claims that copyright forbids using software

### ISSUE THREAD

**Issue by Wuzzy2** [github/choosealicense.com#444]
From http://choosealicense.com/no-license/:

> If you find software that doesn’t have a license, that generally means you have no permission from the creators of the software to use, modify, or share the software.

Wait, what? Even not _using_? I am not a lawyer but this seems surprising to me. But is this actually true? And even if such a restriction applies, is it actually because of copyright law? Or maybe its because of something else?

My gut feeling tells me this claim is false because by the same logic, we would not be allowed by copyright law to “use” copyrighted books (by reading them) because we didn't get permission. ;-)
Can someone who knows more about things like this clear it up, ideally with sources and stuff?

I am also unsure about the “modify” part. Note the text only mentions the modification itself, not the distribution of such a modification. As far my layman knowledge goes, I think copyright is only concerned about copies.

**Comment by mlinksva** [comment]
The website doesn't make the claim the title of this issue claims, but I can see how one could get that meaning. One doesn't need permission of the creators/copyright holders for everything. Various limitations and exceptions to their 'exclusive rights' exist, though not much one can count on, especially worldwide. Probably worth noting that on this page.

Use/using isn't a copyright term (those are reproduction, preparation of derivative works, distribution, and public performance/display/broadcast, eg [U.S. copyright act definitions](https://www.law.cornell.edu/uscode/text/17/106)), but seems like a good word to...use...as it's how people talk/think about software, encompassing various acts which might fall under one or more of copyright owners' exclusive rights.

Is a copyright owner's permission needed to run a program? If you're running it only for yourself, you're still making copies, necessarily, in order to run the program. The [EU directive on computer programs](http://eur-lex.europa.eu/legal-content/EN/ALL/?uri=CELEX:32009L0024) is clear that this is a restricted act, but people who have lawfully acquired software can do it. I don't know that there's as clear a statement in U.S. or other [case] law, but feel free to search and [dis]confirm. If you're running it for other people, you might also be triggering distribution or public performance. These are not completely settled. Software copyright is still a relatively new thing.

This uncertainly does not stop businesses from being shaken down or even raided for simply running software without permission from the copyright holders.

Reading a printed book does not involve making a copy. Digital books and other media does, just like software, making them subject to additional grabs by copyright holders and attendant controversies, e.g., around sale/rental and technical restrictions. So some are concerned about maintaining the "right to read" [long term](https://www.gnu.org/philosophy/right-to-read.en.html).

Yes, preparation of a derivative work is an exclusive copyright owner right, independent of others. Is this insane? Also yes. ("Moral rights" can also come into play here.) Various exceptions and limitations may or may not apply.

You're right that there are other sources of restrictions on using software besides copyright, including contract (eg EULA), technical (eg DRM), and patent. The first two won't be relevant in the complete absence of any license or technical restrictions, as is usually the case for code made public on a platform like here. The last is only relevant for permission from the creator if they happen to also be the owners of the relevant patents.

Thanks for reporting this and #445. I'll try to slightly modify the no-license page text so that readers who wonder like you can be satisfied, while not making it seem that someone who just wants to choose a license or get someone else to for the first time needs to dive into the abyss in order to act.

**Comment by Wuzzy2** [comment]
It's not about “reader satisfaction” but to make sure the text is not misunderstood.

But thanks for looking into this.
