### ISSUE TITLE
EPL 1.0 not appearing in license lists

### ISSUE THREAD

**Issue by waynebeaton** [github/choosealicense.com#449]
I swear that the EPL used to be an option in the license selection drop-down for a new GitHub repository, but it's not showing up anymore.

AFAICT, the license file meets the criteria outlined on the CONTRIBUTING page.

I don't see how the list of licenses is being fed to GitHub. What do I need to do to make this happen?

**Comment by mlinksva** [comment]
The license is at http://choosealicense.com/licenses/epl-1.0/

The license selection drop-down on GitHub eventually (via benbalter/licensee, which vendors github/choosealicense.com) is informed by changes here.

The change you noticed is due to https://github.com/github/choosealicense.com/pull/386

See #413 and #427 for similar discussion.

I can't promise anything but I'll pass along the desire of people who already know what license they want to have that license available in the license selection UI somehow.

Thanks for the feedback! I'm closing this now as I don't think think there's anything to do for this project, but feel free to continue conversation if you have further questions.

**Comment by mlinksva** [comment]
BTW @waynebeaton since I see that you're on the Eclipse Foundation staff, I look forward to adding the next version of the EPL when it is eventually done; made me check the [mailing list](http://dev.eclipse.org/mhonarc/lists/epl-discuss/msg00070.html). Also very nice to see the new [contributor agreement](https://www.eclipse.org/legal/ECA.php) utilizing the DCO!

**Comment by waynebeaton** [comment]
I cannot figure out how to even navigate to the EPL page on the site. Am I just not seeing it? Is there an actual link on the site?

The notion expressed in #386 that the EPL isn't a license that "anyone should choose unless they already know about them because they're in the relevant communities" is incorrect. I just did a quick search to compare hits of the EPL vs the AL and while there are certainly more hits against AL, the numbers are in the same order of magnitude. Lots of people who aren't building Eclipse plug-ins select the Eclipse Public License.

How do we appeal this decision?

**Comment by mlinksva** [comment]
Eclipse and Clojure are pretty big communities, so I'm not surprised that EPL gets lots of hits. Why should someone who is just learning about open source licenses and not in one of those communities (and maybe others I don't know about) learn about EPL?

It isn't linked prominently but can be gotten to at http://choosealicense.com/appendix/ which is linked from the top of http://choosealicense.com/licenses/ and http://choosealicense.com/about/

Also see just added https://github.com/github/choosealicense.com/issues/413#issuecomment-243605410 we're considering how to make more licenses accessible from the drop-down.
