### ISSUE TITLE
Suggestion: replace "provenance" in the /licenses page

### ISSUE THREAD

**Issue by waldyrious** [github/choosealicense.com#458]
It would be better to use a word more people are used to (or can guess the meaning of), like "origin" or "authorship".

**Comment by mlinksva** [comment]
Authorship is too narrow. I really like provenance because it captures documentation of both ownership and other processes that open source licenses can require. Origin might work if it's interpreted really broadly, but at the same time seems really vague. I'm closing this but feel free to make a further argument.

**Comment by waldyrious** [comment]
I'm not sure what meanings "provenance" would provide that "origin" would fail (or not be as effective) to provide. Can you expand a little on what you mean by "other processes that open source licenses can require"?
