### ISSUE TITLE
differentiate X11 and Expat

### ISSUE THREAD

**Issue by s72785** [github/choosealicense.com#465]
On http://choosealicense.com/appendix/ you list MIT although there is different versions [as pointed out](https://en.wikipedia.org/wiki/MIT_License#Variants).

I suggest renaming to "Expat License (sometimes called the MIT license)"[^1] or at least adding "(Expat License)" to the title as this one is approved by OSI and maybe listing X11 separately.

In case you ask "why would this be useful":
* github (amongst others) cannot identify which MIT License is used
* People should be enabled by this service to state properly what they use
* mitigate problems when text was added like e.g. for the (also here endorsed) Projects like jQuery (alos goot ecample that license is not recognized by github)

[^1]: https://www.gnu.org/software/librejs/manual/html_node/Free-Licenses-Detection.html#Detected-Free-Licenses

**Comment by mlinksva** [comment]
Thanks for the suggestions, @s72785. One by one:

1. X11 likely meets our [criteria](https://github.com/github/choosealicense.com/blob/bba25c9cbb64dc7e960b1a3fed6c9e80b1568f7c/CONTRIBUTING.md#adding-a-license), has been discussed previously https://github.com/benbalter/licensee/issues/98 but nobody has made a pull request. Feel free to follow up.
2. Also at https://github.com/benbalter/licensee/issues/98 see references, there are many more variations of the MIT text. The one here seems very widely accepted as the MIT license for many years, which is why it's also at https://spdx.org/licenses/MIT.html from where we take license names. I suspect renaming to Expat or adding a parenthetical now would confuse far more people than it would help. In any case, if you convince SPDX to rename, please let us know (actually our tests will detect it :smile:).
3. Presumably you're writing about license detection on github.com. Adding more licenses won't help with detection when custom text is added as in the the case of [jQuery's LICENSE.txt](https://github.com/jquery/jquery/blob/1b9575b9d14399e9426b9eacdd92b3717846c3f2/LICENSE.txt). The library that handles detection is [licensee](https://github.com/benbalter/licensee). It tries to err on the side of false negatives rather than false positives, so extra text usually means non-detection.
4. By "here endorsed" I guess you must be referring to [listing](https://github.com/github/choosealicense.com/blob/bba25c9cbb64dc7e960b1a3fed6c9e80b1568f7c/_licenses/mit.txt#L13) jQuery as an example MIT licensed project. We [do want](https://github.com/github/choosealicense.com/blob/bba25c9cbb64dc7e960b1a3fed6c9e80b1568f7c/README.md#optional-fields) examples that are straightforward, recognizable, and would be detected by licensee if copied. If you have suggestions for MIT examples that better serve those aims, adding them would make a good issue or pull request.

I'm closing this issue as I don't see an immediate action item, but feel free to follow up on any of the above points individually.
