### ISSUE TITLE
MIT license liability contradiction

### ISSUE THREAD

**Issue by astorije** [github/choosealicense.com#466]
At http://choosealicense.com/:

<img width="305" alt="screen shot 2016-12-09 at 01 26 38" src="https://cloud.githubusercontent.com/assets/113730/21039795/8e103262-bdae-11e6-806f-ed55cc323760.png">

> [...] as long as they [...] don't hold you liable.

And at http://choosealicense.com/licenses/:

<img width="792" alt="screen shot 2016-12-09 at 01 27 38" src="https://cloud.githubusercontent.com/assets/113730/21039815/b816d336-bdae-11e6-9325-8f35cdd873ec.png">

> 🔴 Hold liable

Is there a contradiction here? If yes, then there is a bug, but if not, I guess that would make this issue a duplicate of #412 😅.

**Comment by lee-dohm** [comment]
If you hover over the "Hold liable" text you get this tooltip which echoes the text in your first image:

<img width="317" alt="screen shot 2016-12-08 at 11 15 23 pm" src="https://cloud.githubusercontent.com/assets/1038121/21040829/3af9ee36-bd9c-11e6-95e4-a623795caecf.png">

I agree that the label "Hold liable" coupled with the red dot is a bit confusing though. I suspect that this is a more clear description of the problem behind #412.

@mlinksva what do you think?

**Comment by mlinksva** [comment]
I don't see a contradiction, but please point out exactly if I'm missing something.

Maybe you're pointing out that the MIT short description on the home page reads like the limitation on liability is a license condition ("as long as...") rather than a limitation (a licensee doesn't lose their license if they try to hold licensors liable, rather they just are highly unlikely to succeed in holding the licensors liable). That's why "forbidden" was changed to "limitations" in #361. I didn't make an issue specifically about correcting the MIT home page description because it's included in a larger revamp #429 that I'll revisit eventually, but just the MIT home page description could be edited for accuracy now if someone wants to try. It's hardcoded in https://github.com/github/choosealicense.com/blob/bba25c9cbb64dc7e960b1a3fed6c9e80b1568f7c/index.html#L21

"Hold liable", let's continue figuring out better words for that in #412.

**Comment by lee-dohm** [comment]
The part that made me dig in to this is that the explanation text for the MIT License itself ends with "don't hold you liable" and then the phrasing under Limitations is "Hold liable". From my layman's perspective, without the context that Limitations is meaning limitations on the licensee, the two phrases by themselves appear to be negations of each other. This is why it was confusing to me. I admit that with a few extra minutes of digging that I was able to figure it out. It was the initial cognitive dissonance that I'm hoping we can avoid.

**Comment by inoas** [comment]
Maybe we can add a cross ontop of a red octagon, so that it looks like a stop sign, instead of just a red bullet/circle/ball. that would *communicate* `hold liable: no`

**Comment by benbalter** [comment]
>  the two phrases by themselves appear to be negations of each other. This is why it was confusing to me

In my mind, it's a limitation, in that you *cannot* hold the publisher liable. Just as if it listed "commercial use" as a limitation, you could not use it for commercial use.

**Comment by lee-dohm** [comment]
> In my mind, it's a limitation, in that you cannot hold the publisher liable.

So can we just be explicit with it? "Cannot hold publisher liable"

**Comment by benbalter** [comment]
> So can we just be explicit with it? "Cannot hold publisher liable"

See my comment over in https://github.com/github/choosealicense.com/issues/412#issuecomment-266510347. The other liabilities are "trademark" and "patent use". Since these are limitations, we'd want to change all three to "cannot use trademarks" "cannot use patents". Here, "patents", "trademarks" and "liability" are three limitations (in the sense they are things you can't do, as indicated by the red icon and the limitations heading).

**Comment by astorije** [comment]
Well, I didn't even know there was a tooltip!

I guess it makes sense when you are used to it, but new readers (which are somewhat target audience of this website), it's confusing: the first was I saw when I was browsing about the MIT license was "don't hold you liable" on the homepage and "Hold liable" in the licenses page.

The fact that "Hold Liable" is in the "Limitations" category and therefore must be negated when reading it ("A limitation of this license is that it does not hold author liable") is not obvious at all.
I would find it much clearer if it was saying: "Limitations: Does not hold liable".

There is definitely a tie-in with #412, but even then, it would definitely easier to understand with a negation in "Limitations".

**Comment by mlinksva** [comment]
#467 made some related changes responding to #412. If anyone thinks there's still a distinct outstanding issue here, feel free to comment. Thanks!
