### ISSUE TITLE
What License to choose....

### ISSUE THREAD

**Issue by BenjaminHoegh** [github/choosealicense.com#499]
What license do I need to choose to make sure that nobody sell the code to others and that is a one-license so they need to pay again to use the system in a new place ?

And can somebody please make the descriptions of the diffrent licenses to a language normal people can understand?? now I have ask 7 persons and nobody can answer me what it means, all they say are it can mean multiple things

**Comment by mlinksva** [comment]
What you want isn't an [open source license](https://opensource.org/osd-annotated), which must permit free redistribution and use (see points 1 and 6 at the link), so it's out of scope for this project.

Note you [don't have to choose a license](https://choosealicense.com/no-license/) at all but should be aware of the implications.

Given what you want, you may wish to find and work with a lawyer to get a proprietary license customized to whatever sales arrangements you're envisioning.

**Comment by BenjaminHoegh** [comment]
so no one of those will make this?

 - License does not expire.
 - Can be distributed in 1 project
 - Can be distributed and / or packaged as a code or binary product (sublicensed)
 - Commercial use allowed
 - Can modify source-code but cannot distribute modifications (derivative works)
 - Support provided
 - Attribution to software creator must be made

**Comment by mlinksva** [comment]
@HawkonDK I can see why people are telling you different things -- the features you put in the comment above are completely different form the ones you noted when you filed the issue.

In any case, there's no open source license stipulating the following:

> Can modify source-code but cannot distribute modifications (derivative works)

See point 3 of https://opensource.org/osd-annotated -- an open source license must permit distribution of derivative works.

> Support provided

It's totally OK to offer support for open source software, but this is never done in a project's open source license, which is an offer to the public, and nobody wants to make a generic offer of support to the whole world. Support would usually be handled in a separate agreement with whatever parties you're selling support to.

> Can be distributed in 1 project

I don't know what this means. If you mean it can be _only_ distributed in 1 project, then it's not open source.

If https://opensource.org/osd-annotated isn't making sense to you, you might look at https://choosealicense.com/licenses/ to get a concrete idea of the range of features available in open source licenses, or https://opensource.guide/legal/ for an explanation of how open source licenses work and what kinds of things you may wish to consider when choosing one.

If it turns out that you don't want an open source license, that's fine, but you'll have to get clearer on what you do want, and probably work with a lawyer to get whatever that is.

**Comment by BenjaminHoegh** [comment]
Oh okay my fault

just a little ting...
"This license explicitly states that it does NOT grant you trademark rights, even though licenses without such a statement probably do not grant you any implicit trademark rights."

when it say "you" are that me or the person there use the open source ??

**Comment by mlinksva** [comment]
"You" in those descriptions would be the licensee, the user of the software under an open source license. However, the descriptions really ought to make sense whether the reader is a licensor, licensee, or both, so I've proposed some edits in #500. Thanks!
