### ISSUE TITLE
Enable probot-stale for this repo

### ISSUE THREAD

**Issue by benbalter** [github/choosealicense.com#501]
Any objection to / thoughts on enabling [the probot-stale](https://github.com/probot/stale) integration for this repo to help clean up stale issues?

/cc @bkeepers

**Comment by mlinksva** [comment]
I don't mind stale issues. Honestly, I like them. When a legitimate decade old bug finally gets resolved in an open source project, I'm tickled. Here, all of the ones open I intend to resolve eventually. But if it's bad form to keep issues open with no timeline for resolution/I have terrible taste, feel free to enable bot or otherwise mass close.
