### ISSUE TITLE
Add official license compatibility 

### ISSUE THREAD

**Issue by mzeinstra** [github/choosealicense.com#513]
Some licenses have official 1-way license compatibility like the new EUPL V1.2: http://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:32017D0863

Can we add explicit license compatibilities to the dataset?

I'm also wondering if there could be a loop in those explicit compatibility clauses that license A can be licensed under licence C because the compatibility goes A -> B -> C.

**Comment by mlinksva** [comment]
Hi @mzeinstra compatibility is useful info for people choosing a license or whether to use a project under a particular license. Despite this, I've not tried to add because:

- it's kind of an expert topic
- need a precise definition of compatibility
- there aren't many sources of authority to defer to (explicit compatibility clauses, FSF's statements)
- some explicit compatibility clauses are complicated by being optional
- FSF's statements are not all uncontroversial

Documenting only explicit clauses as you've suggested would be somewhat easier. Feel free to make a concrete proposal for doing this.

A -> B -> C isn't a loop is it? A loop would be A -> B [...] -> A. Both exist, at least among the most recent versions of CeCILL, EUPL, and LiLiQ-R, former can be obtained with only LGPL or MPL-2.0 and GPL and AGPL (depending on precise definition of compatibility anyway).

**Comment by mlinksva** [comment]
Good suggestion, but I don't plan on working on it. If anyone creates an external authority on compatibility we might be able to ingest that. Feel free to comment, open a new issue or PR, etc.
