### ISSUE TITLE
Better handling of angle brackets in licenses

### ISSUE THREAD

**Issue by haacked** [github/choosealicense.com#54]
The licenses we included are intended to be plain text. But since we render them on a website, we have issues with angle brackets. There are two cases we've seen for angle brackets.
1. To denote a template.

```
copyright <your name> <year> <month>
```
1. To denote a URL

```
for more info, visit <http://unlicense.org>
```

As of #53 we plan to manually replace angle brackets with square brackets. The problem we've encountered is that these licenses templates are the same one we use in .com when you pick a license and they are dropped as-is into a repository without the benefit of Jekyll processing.

So what I propose we consider, if possible:
1. License templates have the license in exactly the original plain text format.
2. When rendering to the web, replace angle brackets with &lt; and &gt;
3. Unless the contents start with "http:" or "https:" in which case we render it as a link. The copy and paste mechanism should still get the original text.

I have a feeling the inclusion of the angle brackets in the source might be a problem for Jekyll though, is that right @benbalter?

**Comment by bhuga** [comment]
Turns out we need to do something here. I'm having trouble with the license picker when [http://...] is the same as [variable]. Bleh.

> License templates have the license in exactly the original plain text format.

These vary, so I would call this a non-goal. We need them standard; some had `{}` in the originals. I propose:
1. `[name]` is a variable
2. `<http://...>` is a URL. Rendered in web as a link, and as plain text with our without `<>` in copy-paste.
3. `{text}` is a non-interpolated variable in license text, akin to https://github.com/github/choosealicense.com/blob/gh-pages/licenses/gpl-v2.txt#L360

**Comment by benbalter** [comment]
The delimiter is arbitrary, just need to decide on a standard.

> [name] is a variable

:+1:

> {text} is a non-interpolated variable in license text,

Got to double check that that doesn't trip up Jekyll, but I think we'll be fine (Jekyll uses `{{`)

> http://...

I don't want to get in the business of doing more work than we have to. Jekyll has a built in filter `xml_escape` which will convert everything to HTML entities for us, or we could just find and replace the `<`s as `&lt;`s. But don't know that we have to make it a hyperlink.

Otherside of the coin, if we start mixing HTML with plain text, is the copy button. The copy button will grab the HTML version (I believe) so we'd have to convert back to plain text on the fly (which is a pain).

I'd recommend leaving URLs as non-html, non-links for simplicity sake, but we may have to swap the HTML entities back to text before they hit the clipboard, which is significantly easier.

/cc @holman because .com

**Comment by bhuga** [comment]
> I don't want to get in the business of doing more work than we have to. 

There's another option, then: no links, no angle brackets. `<http://fsf.org/blah/>` becomes `http://fsf.org/blah/`.

Or we could go back to the double angle brackets, but only use them for URLs instead of URLs and variables?

**Comment by benbalter** [comment]
> Or we could go back to the double angle brackets

I believe we'd have to escape them though, otherwise they'd get parsed as malformed HTML, right?

**Comment by bhuga** [comment]
Wait, sorry. Double angle brackets are a no-go on .com, unless we duplicate the search/replace. That okay?

**Comment by bhuga** [comment]
I took a stab at this with #55:
1. `<` is just `<` on .com
2. `<` is `[` on choosealicense.com
3. `[` is a variable
4. `{` just is.

**Comment by haacked** [comment]
@bhuga can we close this now?
