### ISSUE TITLE
Create clear standard instructions for adding LGPL to a GitHub repository

### ISSUE THREAD

**Issue by colosi** [github/choosealicense.com#607]
It would be ideal if all instructions and flows provided by GitHub matched each other and were what was created when you generate a new repository with a license template included or at least if choosealicense made it clear that you should ignore the GNU instrucitons and the basic license flows in the case of the LGPL, where a few extra steps should be taken.

1. GNU says to put the GPL in COPYING and LGPL in COPYING.LESSER
2. choosealicense says to put the GPL in LICENSE and LGPL in COPYING.LESSER -- Is this a mistake or did choosealicense intend for two different base file names?
3. Choosing the LGPL as the license template at repository creation generates only LICENSE with the LGPL (no GPL)
4. Following the GitHub blog instructions for adding a license to an existing repository generates only LICENSE with the LGPL (no GPL)

Quickly examining a handful of LGPL repositories, most didn't include the GPL anywhere.

I've seen users suggest using LICENSE and LICENSE.LESSER as these are a broader standard outside of the linux community where the standard is COPYING for the license file.

So, what is the standard for GitHub?  If I follow the instructions on choosealicense and use LICENSE and COPYING.LESSER, will the LGPL be properly detected as the repository license, or will it think the repository is under the GPL?

**Comment by mlinksva** [comment]
> If I follow the instructions on choosealicense and use LICENSE and COPYING.LESSER, will the LGPL be properly detected as the repository license, or will it think the repository is under the GPL?

It'll be detected as LGPL. The code that does this is in https://github.com/benbalter/licensee/blob/1961b0e82d6c92242f5403d7fd41c5053aa3f8d5/lib/licensee/projects/project.rb

On your points 1 and 2, I agree the instructions here could be more consistent. I'll leave this open until it is fixed.

Point 3 can't be addressed in this repository. I'm not sure it's a big practical problem; LGPL will be detected by itself. I'll pass the feedback along though. On point 4, I'm not sure what blog instructions you're referring to, but I suspect it is the same as point 3.

**Comment by colosi** [comment]
> On point 4, I'm not sure what blog instructions you're referring to

Sorry, it was not from a blog.  It is a help article - https://help.github.com/articles/adding-a-license-to-a-repository/

**Comment by dcousens** [comment]
When you specify the license as `GNU Lesser Public...` when creating a new repository on GitHub,  it only creates a license file with the LGPL additions.   The GPL is NOT included.

As mentioned by @colosi,  to provide users with the LGPL license,  [GNU recommends](https://www.gnu.org/licenses/gpl-howto.html) that you:

> Add a COPYING file with a copy of the GNU GPL or GNU AGPL.
>
> Also add a COPYING.LESSER file with a copy of the GNU LGPL, if you use that.

I think the @GitHub default of only including the LGPL additions,  but completely missing the rest of the license is quite broken.

**Comment by mlinksva** [comment]
> On your points 1 and 2, I agree the instructions here could be more consistent. I'll leave this open until it is fixed.

In #709 I specified only COPYING for GPL-3.0 so as to make the instructions between the [L]GPL-3.0 consistent.

As to the behavior on github.com, this repository can only address this to a very limited extent: the license picker can't add multiple files at this time, and this repo isn't a place to fix that. I've changed the Lesser GPL 3.0 metadata to make it less likely it will be arrived at through the picker (eventually; code from this repo ends up supporting the picker via being vendored in licensee) and hid the sidebar form on choosealicense.com for LGPL-3.0 which leads to the picker.

**Comment by jlumbroso** [comment]
@mlinksva Respectfully, I think you implemented the wrong solution to this thread.

Although @colosi discusses standards in terms of the choosealicense.com workflow, their concern seems to be to make sure that the licenses are properly detected. That sounds like a [licensee](https://github.com/licensee/licensee) issue, not a choosealicense.com issue.

Next, I disagree with @dcousens that the previous behavior of choosealicense.com for LGPLv3 was "_broken_": The added terms of the LGPLv3 are fine to understand, unambiguous, and have been used for years without an issue. They are appropriately detected by GitHub and serve to report on the usage of LGPLv3. (What would be great is if variants described by @colosi could also be properly detected—but since currently the Licensee API does not even detect licenses that are in Markdown, I don't think its accuracy should drive design decisions.)

I think what is "_broken_" is that two users with no affiliation that I can see to @github have been able to convince the company to restrict choice for ALL users that use GitHub/choosealicense.com.

Indeed for new programmers, removing LGPLv3 as an option in the license picker may very well just make them unaware of LGPLv3.

**I suggest that https://github.com/github/choosealicense.com/pull/709 be reversed.** If @dcousens would like to not use this, they do not have to! 😖 We can discuss with @colosi how to update Licensee for better detection as a separate conversation.

**Comment by NumesSanguis** [comment]
Just to add my experience to this discussion.

It seems LGPLv3 is detected if you have a LICENSE and LICENSE.LESSER file: https://github.com/licensee/licensee/issues/287#issuecomment-1689554311

It was confusing to me though that LGPL-3.0 was not an option anymore, because I could select it in the past. I almost selected LGPLv2.1 because I wanted it to be LGPL. Had to guess from https://choosealicense.com/licenses/lgpl-3.0/#how-to-apply that it is no longer an option because technically the old approach was not correct. I manually had to add an extra file.

By having both files, my repo is indicated as `GPL-3.0, LGPL-3.0 licenses found` as opposed to just ` LGPL-3.0 license ` though.

**Comment by Florifulgurator** [comment]
"COPYING.lesser" seems the right thing. Why not add that to the help article.
It is utterly bizarre that you need to study some source code if you want to correctly add LGPLv3 :-D
