### ISSUE TITLE
Bring back CC0

### ISSUE THREAD

**Issue by tordanik** [github/choosealicense.com#61]
I was pretty excited to learn that CC0 was among the legal texts available on choosealicense.com and that I could even choose it during repo creation. I love CC0 and advertise it to artists and developers alike: It's attached to the strong Creative Commons brand and equally applies to all types of creative works (unlike the limitation to software found in the Unlicense).

Of course that's just the opinion of one guy, but consider that the FSF [explicitly recommends CC0 over Unlicense](http://www.gnu.org/licenses/license-list.en.html#Unlicense) and that there's a [wealth of CC0 media files](http://commons.wikimedia.org/wiki/Category:CC-Zero) already available.

So I hope you understand why I'm a bit disappointed about the resolution of #38. By no means do I want to put down the effort of the Unlicense people, their advocacy for the PD cause is excellent! But I believe the point of PD is simplicity, and to me that means the ability to use the same declaration for my software, its wiki, manual, screenshots, and many other things up to my holiday photographs and videos.

**Comment by paulmillr** [comment]
+1.

See this nice short answer on what is wrong with unlicense http://programmers.stackexchange.com/questions/147111/what-is-wrong-with-the-unlicense

Please change “public-domain” unlicense to cc0.

**Comment by ghost** [comment]
I'd salute addition of both CC0 and Unlicense. I have no beef in this issue at all, I'd only point out that unfortunately, each of the public domain dedications referenced here have their downsides. Real or not, but disputed. CC0 is not OSI approved, and the reason is around the fact that it explicitly reserves patent rights. An example, its withdrawal thread: http://projects.opensource.org/pipermail/license-review/2012-February/000231.html

Nevertheless it's clear to me what their intention is: public domain dedication, through the means available, more or less disputable, and with no legal precedent.

**Comment by eric-brechemier** [comment]
I agree that both options should be included, at least in the drop-down in the form to create new repositories on GitHub. I see no reason to replace CC0 with Unlicense when the FSF actually recommends CC0 over Unlicense for Public Domain dedication of software.

**Comment by benbalter** [comment]
See https://github.com/project-open-data/project-open-data.github.io/pull/135 for a great discussion on the relative merrits of CC0 and Unlicense.

**Comment by haacked** [comment]
Very interesting @benbalter. I see you went with CC0 there. The lack of lawyer vetting is concerning.

After reading that discussion, I'm more inclined to including both, but grouping them under the "Public Domain" family. See #111 for what I mean by grouping them. I'd probably keep Unlicense as the primary one though.

But it would be nice to get some more lawyers involved in vetting Unlicense.

**Comment by benbalter** [comment]
> The lack of lawyer vetting is concerning... But it would be nice to get
> some more lawyers involved in vetting Unlicense.

IANAL (officially), but law isn't like organic food, where you need someone
to certify it... all you can do is mitigate risk. In the project open data
thread, which I believe was linked earlier, you'll note that it's gotten
plenty of smart people's eyeballs.

Lawyer's are naturally risk averse, and are always going to prefer CC0 over
something like the unlicense (or Apache or MIT) just because there more
lawyering there.

Hoping to take a closer look at the grouping, but a big :+1: to a public
domain grouping with the Unlicense as primary.

**Comment by JoshData** [comment]
This can probably be closed now that #126 is merged.
