### ISSUE TITLE
Mention licenser CLI script

### ISSUE THREAD

**Issue by twilligon** [github/choosealicense.com#629]
I wrote a [shell script](https://github.com/milkey-mouse/scripts/blob/master/licenser) that can fetch licenses from this repo straight into a `LICENSE` file, just like GitHub does it when you check the "Initialize repository" box. Perhaps this is just shameless self-promotion (in which case sorry for wasting time & an issue) but would it be useful to link to it somewhere on choosealicense.com or in the README?

I would be happy to relicense it, move it to a dedicated repo, etc. although I doubt that would be necessary since it's already public domain.

**Comment by mlinksva** [comment]
Thanks for letting us know @milkey-mouse ... I've run across other scripts that use data from this repo to select/populate licenses from the command line. I don't think we have a good place to document right now on the site/in the repo but this issue is a good start. I'm going to close for no immediate action, but try to remember to note similar scripts here and maybe document more prominently at some point.
