### ISSUE TITLE
Set Line Width to 78 Characters

### ISSUE THREAD

**Issue by derks** [github/choosealicense.com#74]
It is pretty common for text editors, and IDE's to default line wrapping to 78 characters.  It can be annoying to have to modify every license because it breaks to 'early', messing with the format.  

It would be appreciated to require that the content of all licenses not exceed 78 characters.  I'll be more than happy to submit a pull request if this is something that will be accepted.

**Comment by haacked** [comment]
Seems fine with me. I'm surprised we're not already at 78 chars. Are all of them wrong? Or just a small set?

**Comment by derks** [comment]
I checked a few... seems like they are off by one or two... probably 80 characters causing the last word of most lines to wrap at 78 chars.

**Comment by haacked** [comment]
Yeah, I always thought 80 characters was most common in terminals and such. How'd you pick 78 and not say, 76 or 79? I'm not trying to be confrontational here mind you. Just curious. I'm used to editors that don't line wrap so I'd love to be educated here. :smile:

I guess 78 would make sense if the 80 char count included CR and LF.

**Comment by artob** [comment]
Back when we formulated the [Unlicense](http://unlicense.org), there was a discussion on whether the hard line wrap should be 78, 76, or 72 characters. We decided to eventually go with the most conservative 72 characters, since that e.g. facilitates copy-and-paste [use in email](http://stackoverflow.com/questions/459281/do-you-use-word-wrapping-within-emails). Just something to consider in case you're going to change them anyhow.

**Comment by haacked** [comment]
So one thing I'd like to do is keep licenses consistent with what has traditionally been on GitHub. Also, when in doubt, I follow WWMD (What would @mojombo do?). https://github.com/mojombo/jekyll/blob/master/LICENSE is set at 78 chars.

Let's go with `78`. :)

**Comment by rtomayko** [comment]
:+1: 78 chars and really appreciate the attention to detail here. Nailing the text formatting on these licenses is one of the main reasons I personally wanted this project to exist in the first place since it's almost always overlooked / not considered important on most license sites. :heart::heart:

**Comment by haacked** [comment]
@derks: would you be interested in submitting a PR for those that need fixing? We recently updated a lot of them using the plain text version supplied to us by the source. Hopefully there aren't too many that need it.

**Comment by haacked** [comment]
Oh wait, this was merged already, wasn't it?

**Comment by haacked** [comment]
![Uploading thumbs-up-basketball.gif . . .]()

Thanks!
