### ISSUE TITLE
<!-- removed -->

### ISSUE THREAD

**Issue by uqsme** [github/choosealicense.com#761]

**Comment by mlinksva** [comment]
MulanPSL-2.0 likely does not yet meet our usage requirements -- https://github.com/search?q=%22Mulan+PSL+v2%22+filename%3ALICENSE obtains 89 hits -- but should otherwise qualify. See https://github.com/github/choosealicense.com/blob/21b959fc2858835884a9fa2966a34f60502b0eeb/CONTRIBUTING.md#adding-a-license for details on the requirements.

Feel free to open a PR for adding this license, and we'll merge when all requirements are met.

**Comment by ianharrd69** [comment]
I own it

**Comment by TheInterestingSoul** [comment]
now 2289 hits. all [conditions](https://github.com/github/choosealicense.com/blob/21b959fc2858835884a9fa2966a34f60502b0eeb/CONTRIBUTING.md#adding-a-license) listed are met.

3 notable projects:
https://github.com/opengauss-mirror/openGauss-server
https://github.com/OSCPU/NutShell
https://github.com/gzu-liyujiang/Android_CN_OAID

**Comment by mlinksva** [comment]
Fixed by #818
