### ISSUE TITLE
License in apache-2.0.txt is missing initial newline causing content and checksum to differ from official upstream file

### ISSUE THREAD

**Issue by dwalluck** [github/choosealicense.com#762]
Compare checksum and content of the generated file to https://www.apache.org/licenses/LICENSE-2.0.txt. They should match.

**Comment by mlinksva** [comment]
Adding an extra newline (or any number of extra newlines) in this repo doesn't result in the generated file having an extra newline, I think due to the way some Ruby library (the site is rendered with Jekyll) splits front matter from content. In any case, I'm not worried about it -- I don't know of any in the wild license matching that only uses the exact checksums of licenses or doesn't have a healthy amount of resilience to whitespace only changes, newermind leading newline only changes.
