### ISSUE TITLE
Font license recommendation (OFL) needs updating to include SPDX 3.8 additions

### ISSUE THREAD

**Issue by n8willis** [github/choosealicense.com#795]
SPDX 3.8 updated the identifiers for the Open Font License (OFL) to distinguish between the two variations "with RFN clause" and "with no RFN clause". (See https://github.com/spdx/license-list-XML/pull/965 for details.)

That was done because the Reserved Font Name (RFN) clause is a licensor-chosen optional clause, but choosing to invoke it for a project substantially changes the compliance requirements for downstream. Not being able to distinguish between them meant some trouble for Debian package maintainers, and probably others.

The Choose A License section for fonts ought to also be updated to recommend the specific "with" or "without" license identifiers, rather than the older, ambiguous one. (Or, of course, it could recommend one or the other; I'm not taking a stance. Just noting that the ambiguous old identifier could use replacing.)

**Comment by mlinksva** [comment]
There's no difference in the license texts, right?

I think we'll have to handle in the same way we do -only and -or-later for *GPL, see https://github.com/github/choosealicense.com/blame/50e1c110548545b3ec5072442942be2548a76a48/_includes/sidebar.html#L27-L29 #563 #421

Welcome thoughts/corrections/a PR!

**Comment by n8willis** [comment]
Correct; the text of the license has not changed; this reflects a choice that the licensor makes solely via their copyright statement / license-declaration. The sidebar presentation definitely looks like an appropriate approach.

**Comment by mlinksva** [comment]
I see, the text of the license is not changed, but there would be added text following the (c) in a LICENSE file for a project with a RFN. I hadn't looked closely enough at first--the SPDX XML files capture this. Thus it would be possible to catalog -no-RFN and -RFN as separate "licenses" here. That might be the right thing to do longer term.

Based on https://github.com/search?q=filename%3ALICENSE+%22open+font+license%22 (49k) https://github.com/search?q=filename%3ALICENSE+%22open+font+license%22+%22with+reserved+font+name%22 (8k) (very rough search) perhaps -no-RFN is about 80% of the use of OFL. Does that jibe with your experience/data?

https://github.com/search?q=license%3Aofl-1.1 only obtains 4k repos, probably because font license files are often in subdirectories, not the main license for a project, and because RFN uses likely wouldn't be detected by licensee either because it's not expecting RFN text, and because once people modify a license file, they're likely to further muck it up. 😄 

For now I took the sidebar approach with #796. Let me know what you think.
