### ISSUE TITLE
Add the Zlib license

### ISSUE THREAD

**Issue by ghost** [github/choosealicense.com#82]
I think it'd be great to add the Zlib license, the big thing with that license is the requirement for Modified verisons of the code to be marked as such 

http://www.tldrlegal.com/license/zlib-libpng-license-(zlib)

**Comment by ghost** [comment]
I'll note that it's OSI approved. http://opensource.org/licenses/Zlib

If it's acceptable to add it, I'll be happy to submit a pull request.

**Comment by haacked** [comment]
Thanks for the suggestion! Right now we're trying to keep the number of licenses we include to a reasonable number. You can see the [about page](http://choosealicense.com/about/) for our reasoning.

If this is a wildly popular widely used license and I haven't heard of it due to my own ignorance, feel free to back that up with some info and we can always reconsider. :smile:

**Comment by r-lyeh-archived** [comment]
this is something quite common nowadays. my upvote for a zlib/libpng license section

**Comment by r-lyeh-archived** [comment]
specially when i want to perform an addalicense.com with zlib/libpng to all my repos : )
