### ISSUE TITLE
License-chooser similar to creativecommons' version

### ISSUE THREAD

**Issue by Andre601** [github/choosealicense.com#825]
[chooser]: https://creativecommons.org/choose/

[site]: https://choosealicense.com

[mit]: https://choosealicense.com/licenses/mit/
[gpl]: https://choosealicense.com/licenses/gpl-3.0/
[wtfpl]: https://choosealicense.com/licenses/wtfpl/

[community]: https://choosealicense.com/community/
[non-software]: https://choosealicense.com/non-software/

[others]: https://choosealicense.com/licenses/
[licenses]: https://choosealicense.com/appendix/

## Idea
Choosealicense.com should receive a way to select a license, similar to [creativecommons' license chooser][chooser].

The user would be able to define one or multiple conditions and based on those would get recommended licenses to choose from.

## Why?
The way the site currently displays and showcases licenses is... limited?
The [main page][site] of the website by default lists two popular ones, [MIT] and [GNU GPLv3][gpl], mentions licenses [preferred by the community][community], those [available for non-software][non-software] and [a few others][others].

The [vast majority of licenses][licenses] however is not mentioned anywhere on that page and can only be found on a separate, kind of hidden page.
This goes against the "non-judgmental guidance on choosing a license for your open source project" in my opinion since the site clearly picks favourites over others as shown by the licenses page linked before.
What if you don't want to use [Unlicense] but instead [WTFPL]? What if the [MIT] doesn't meet all requirements you have for the license but the site doesn't mention an available license from the appendix that would fit those?

A license chooser could help by giving exposure to other licenses and increase their chance of being selected for projects. Plus it could help users finding a more fitting license for their specific needs.

**Comment by mlinksva** [comment]
Feel free to create/prototype something like this, though I can't promise to use it on choosealicense.com. I dislike the CC license chooser, would rather they just present the licenses available as a spectrum. That's probably a big part of why choosealicense.com/licenses is how it is. 😄 

The site is non-judgmental as to what characteristics an open source license should have, largely meaning it's agnostic about copyleft/permissive, and tries to just give facts about licenses.

It doesn't try to surface all of the options that are highly similar to each other. I have played with this locally but didn't come up with anything that'd be useful. WTFPL didn't show up as an alternative to Unlicense, by the way, because it doesn't have the same characteristics (lacks warranty/lability disclaimers).
