### ISSUE TITLE
0BSD licence doesn't have a title

### ISSUE THREAD

**Issue by x13a** [github/choosealicense.com#837]
Hello. 

The problem is simple. 0BSD license doesn't have a title. There was [commit](https://github.com/github/choosealicense.com/pull/643/commits/bab9f14fa93405fead73948946c8ca9c2b62c1c5) when it was remove because SPDX doesn't have it too. Without a title or the help of github, I suppose, people can't understand what the license it is. If add a title to the license, github shows it as `Other`. To show it correctly and address that it is 0BSD, file name changes from `LICENSE` to `LICENSE-0BSD`. I dislike this. That is why I am here.

**Comment by mlinksva** [comment]
> If add a title to the license, github shows it as `Other`

Could you point out where you've seen this?

I've tested locally, and licensee (which GitHub uses) tolerates either `0BSD` or `BSD Zero Clause License` or even `BSD Zero Clause License (0BSD)` added to the top since it knows those are the SPDX ID and name, even though they aren't part of the canonical license text.

I'd rather not make changes to license texts here that aren't reflected in the SPDX versions. I'm going to close this as it likely isn't an issue for this repo, but do please add an example of the behavior you note above, as it may be an issue for licensee.

**Comment by mlinksva** [comment]
Nevermind, found it at https://github.com/x13a/go-launch/commit/f7e43221ed3e6e4bdcef54a0f3426d1e6f27d10a

I see you had `Zero-Clause BSD (0BSD)`. If instead you used one of the options above, it would have been detected.

**Comment by x13a** [comment]
Oh. Its is my fault. I have used a title from [opensource.org](https://opensource.org/licenses/0BSD) and have not tried to use SPDX id or name. Thank you very much for the explanation)

**Comment by waldyrious** [comment]
spdx/license-list-XML#1297 has been merged, so perhaps this could be reopened.

**Comment by mlinksva** [comment]
Thanks for the SPDX and followup here #843 PRs. LGTM so I'll go ahead and merge without reopening this.

**Comment by waldyrious** [comment]
@mlinksva I'm thinking we should update the usage examples for this license to include at least one that has the title. None of the current ones do:

- [PickMeUp](https://github.com/nazar-pc/PickMeUp/blob/master/copying.md)
- [smoltcp](https://github.com/m-labs/smoltcp/blob/master/LICENSE-0BSD.txt)
- [Toybox](https://github.com/landley/toybox/blob/master/LICENSE)

From a quick search, [gatsbyjs/gatsby-starter-default](https://github.com/gatsbyjs/gatsby-starter-default/blob/master/LICENSE), [Codelessly/ResponsiveFramework](https://github.com/Codelessly/ResponsiveFramework/blob/master/LICENSE) and [holtzy/The-Python-Graph-Gallery](https://github.com/holtzy/The-Python-Graph-Gallery/blob/master/LICENSE) seem to be popular projects under 0BSD that use the title.

My question is whether we should replace all three existing examples with the ones that do have titles, or remove just PickMeUp because it also doesn't have a copyright line (or keep it precisely because of that!), or remove the first two for lacking the title, but leaving Toybox for historical reasons, or something else entirely. Let me know what you think!

**Comment by mlinksva** [comment]
@waldyrious I don't feel strongly, am basically fine with 3 examples that can be copied without leading users astray and from projects that have some level of popularity/maintenance/renown and ideally from different maintainers and languages. So I don't think any changes are necessary but if you want to fine-tune, perhaps including an example with both title and notice, one with neither, and one with only copyright notice, go ahead and make a PR.

**Comment by waldyrious** [comment]
> perhaps including an example with both title and notice, one with neither, and one with only copyright notice

That sounds perfect. I'll submit a PR.

Btw, interestingly, the first two of the existing examples don't seem to be detected by licensee (the header isn't shown in GitHub). I suppose the title might give the matcher additional confidence.

**Comment by mlinksva** [comment]
The LICENSE files of the first two existing examples simply haven't been changed (thus re-detected) since 0BSD became known to licensee, thus aren't being shown in the GitHub UI. Licensee can definitely detect them (or tests in this repo would fail 😄 ).

**Comment by waldyrious** [comment]
Ah, that's reassuring. I was indeed a little puzzled by the difference in detection.
