### ISSUE TITLE
Distribution and original authors?

### ISSUE THREAD

**Issue by afeld** [github/choosealicense.com#92]
Saw [this Quora question](https://www.quora.com/MIT-License/If-i-fork-someones-repo-on-github-licensed-under-mit-license-and-make-some-changes-can-i-release-it-under-my-name):

> If i fork someone's repo on github licensed under mit license and make some changes, can i release it under my name?

and, at least in my reading, none of the tooltips say specifically yay or nay.  Or does this fall under "Sublicensing"?

/cc @hoolio

**Comment by hoolio** [comment]
As a lawyer, answering this sort of thing makes me nervous since it starts looking like I'm giving legal advice to strangers and potentially establishing some sort of attorney-client relationship. 

The answer is ... sort of. 

You're allowed to release the new project under your own name, but the MIT license requires you to keep the copyright attribution notice from the original. 

In other words, you end up with something that is released under your name (e.g., Julio's Eatery App), but that in the documentation somewhere still includes a line that says "Copyright (c) <2013> <Tom Werner>

**Comment by afeld** [comment]
I personally think we are best off providing the "safe" recommendation, which in this case would be to include both copyright statements, no?

```
The MIT License (MIT)

Copyright (c) 2013 Julio's Reasonable Advice
Copyright (c) 2014 Aidan's Cowboy Advice

Permission is hereby granted...yadayadayada
```

**Comment by haacked** [comment]
Closing this since there's nothing actionable. Feel free to continue the discussion. I'm curious to what @hoolio and @talniv think are best practices in this regard. :smile:

**Comment by benbalter** [comment]
/cc #97:

> Issues should be limited to site improvements

If the issue has been authoritatively decided elsewhere, feel free to open an issue to implement (and ideally link to) that guidance here.

**Comment by ghost** [comment]
I think it can be a site improvement, but it's beyond the scope of choosealicense.com, as far as I see. It amounts to how to apply your license over a project that contains open licensed code from someone else. Common occurrence of course, but it would mean expanding the license chooser to a compliance tool...

**Comment by dexterous** [comment]
If your fork is strictly derivative, i.e. has material modification from original, does the copyright of the upstream author need to be maintained; esp considering the copyright pertains to the entire contents of the repo?
