### ISSUE TITLE
Add Server-Side Public License (SSPL)

### ISSUE THREAD

**Issue by vhscom** [github/choosealicense.com#932]
https://www.mongodb.com/licensing/server-side-public-license
https://spdx.org/licenses/SSPL-1.0.html

This license is notable enough to have its own Wikipedia page so it should probably be added here too. Please note this license is the spiritual succesor to AGPLv3 and also based on GPLv3 with a modified section 13 to explicitly prevent what AGPL tried to in the first place:

![Screenshot from 2022-01-16 16-49-43](https://user-images.githubusercontent.com/97140109/149653445-ecfcab20-8e55-426a-8533-ac592b6f659d.png)

**Comment by Tyler887** [comment]
@vhscom, this license is not osi nor fsf approved. For open source network services I recommend the AGPL which **is** FSF approved. Read the [contributing guidelines](https://github.com/github/choosealicense.com/blob/20d853259a9412aa7a0d6f6d9bc0f098f38266d9/CONTRIBUTING.md).

**Comment by vhscom** [comment]
Thanks for considering the inclusion of the SSPL license. While it may not conform to the OSI or FSF definitions of "approved" licenses it's intention is to protect users from gaps in AGPL. Sometimes it's necessary to break the mold in order to improve the future.

**Comment by vhscom** [comment]
Thanks for considering the inclusion of the SSPL license. While it may not conform to the OSI or FSF definitions of "approved" licenses its intention is to protect users from gaps in AGPL. Sometimes it's necessary to break the mold in order to improve the future.

**Comment by JasonGoldman** [comment]
Referencing SSPL would make this website more relevant to today's developers. The upcoming [Open Source Definition](https://github.com/CollectiveSource/Open-Source-Definition) (v1.11) will acknowledge SSPL as an open source license.

**Comment by huan** [comment]
I second @vhscom and @JasonGoldman for supporting add SSPL to GitHub's License list.

My [reasons](https://github.com/Chatie/community/issues/1) is:

1. From the Server Side Public License FAQ, we can learn that the SSPL is the same as the AGPL, but make "Section 13" clear that "Remote Network Interaction"(AGPL) explicitly includes "Program as a Service"(SSPL) because the "Program as a Service" is definitely the cloud-native version of "Remote Network Interaction".
1. It's a shame that the OSI had not added the SSPL to their License list, I believe it's because there are lots of interest conflicts from the community who governed the OSI.
1. I love [Open Source Definition](https://github.com/CollectiveSource/Open-Source-Definition) because it's damn right: the Arbiter should be the **Community** instead of ~~OSI Corporation~~

I will use SSPL for my Chatie.IO projects later, and I'd love to select the SSPL from the GitHub list, instead of creating them manually.
