### ISSUE TITLE
Missing license option for software that generates hardware

### ISSUE THREAD

**Issue by riskable** [github/choosealicense.com#933]
What sort of license would be appropriate for something like https://github.com/riskable/void_switch ?  It's software that generates hardware (3D printable objects).  I want it to be free for non-commercial use (businesses have to pay) and to require that changes/forks remain open source.

If I made it say, GPL then businesses could use the software freely to 3D print and sell the switches without giving back a damned thing. They could also modify the files generated by the software after they had been generated and those changes would not be required to be open source.

Creative Commons licenses also don't apply since it's software that generates hardware.  Is it even possible to attach a license to what gets generated by the software?  It's super confusing.

Googling around has only lead to more questions, LOL.

**Comment by mlinksva** [comment]
I don't know that a license to do exactly what you describe exists.

> I want it to be free for non-commercial use (businesses have to pay) and to require that changes/forks remain open source

CC-BY-NC-SA is kind of like that, but not exactly, since NC is not technically open, and doesn't require source. 😄  

> Is it even possible to attach a license to what gets generated by the software?

Might depend on what you mean by "generated by the software"; not sure how analogous your project is to any other [open] hardware design project where the "software" is the "design" or you have something unique. I'd suggest looking up on research done by the open hardware community, one recent overview that may be helpful https://www.youtube.com/watch?v=Lg0BcLdfV-I

The usual goal pursued by free or open projects is not to prevent business from using, but require them (and anyone) to share if they modify. Look into whether a strong copyleft license such as GPLv3 or perhaps CERN-OHL-S-v2 (which will probably eventually be added to this repo in https://github.com/github/choosealicense.com/pull/854) might work for you.
