### ISSUE TITLE
Include a "wizard"

### ISSUE THREAD

**Issue by waldyrious** [github/choosealicense.com#96]
The description "Like a Choose Your Own Adventure site" isn't really accurate unless a wizard-like workflow is established to guide users through several choices, reaching the final result. A good example of such a wizard is the one from [WikiMatrix](http://www.wikimatrix.org/wizard.php).

Nothing complex or fancy is needed to implement this. A simple tree of hyperlinked pages would do, similar to [John Cowan's FLOSS license selection wizard](http://home.ccil.org/~cowan/floss/).

**Comment by benbalter** [comment]
That is the purpose of the landing page.

![screen shot 2013-10-03 at 2 01 56 pm](https://f.cloud.github.com/assets/282759/1263759/eb4796fc-2c55-11e3-8f10-bc7597db2f45.png)

Here, we've simplified the choice of which license to choose to a single question. It's an adventure, it's just a short lived one. :smile:

**Comment by waldyrious** [comment]
Yeah, I got that :) – but I really think a full choice tree including all the current qualifiers ("License and copyright notice", "State Changes", "Disclose Source", etc.) would be valuable.

**Comment by haacked** [comment]
Well, we're hoping to keep the number of licenses low enough that such a thing isn't really necessary. You don't need a "choose your own adventure" game to choose among three licenses. :smile:

We're trying to avoid license proliferation. Most people don't need so much customization of their license, but would be best served by choosing one of the three most popular licenses. Or by a license popular with their community. For example, jQuery plugin authors tend to choose MIT because jQuery is MIT.

A choose-your-own-adventure approach is also very fragile. Minute differences in wording can suddenly cause people to choose a license against their own interests. Also, traits such as "disclose source" might mean slightly different things for each license. This means to be fair, each question in the adventure would have to be convoluted so people don't dismiss the option because of a technicality.

So for now, I'm :thumbsdown: to this idea.

I guess my question for you is, did you have trouble choosing a license?
